<!ELEMENT students (student+)>

<!ELEMENT student (first, middle?, last, preferred?, email, phone?, year, gpa, major, minor, status, advisor, admit, grad?)>
<!ATTLIST student id CDATA #REQUIRED>

<!ELEMENT first (#PCDATA)>
<!ELEMENT middle (#PCDATA)>
<!ELEMENT last (#PCDATA)>
<!ELEMENT preferred (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT gpa (#PCDATA)>
<!ELEMENT major (#PCDATA)>
<!ELEMENT minor (#PCDATA)>
<!ELEMENT status (#PCDATA)>
<!ELEMENT advisor (#PCDATA)>
<!ELEMENT admit (#PCDATA)>
<!ELEMENT grad (#PCDATA)>
